<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Family;
use App\Models\Subcategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FamilySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $families = [
            'Comestibles' => [
                'Frutas' => [
                    'Banana',
                    'Manzana',
                    'Pera',
                    'Naranja',
                    'Mandarina',
                    'Kiwi',
                    'Durazno',
                    'Ciruela',
                    'Uva',
                    'Sandía',
                    'Melón',
                    'Pomelo',
                    'Limón',
                    'Ananá',
                    'Frutilla',
                    'Arándano',
                    'Cereza',
                    'Mora',
                    'Frambuesa',
                    'Mango',
                    'Papaya',
                    'Maracuyá',
                ],
                'Verduras' => [
                    'Lechuga',
                    'Espinaca',
                    'Acelga',
                    'Rúcula',
                    'Jengibre',
                    'Zanahoria',
                    'Remolacha',
                    'Papa',
                    'Batata',
                    'Zapallo',
                    'Calabaza',
                    'Berenjena',
                    'Tomate',
                    'Morrón',
                    'Cebolla',
                    'Puerro',
                    'Cebollita de verdeo',
                    'Choclo',
                    'Arveja',
                    'Chaucha',
                    'Poroto',
                    'Alcaucil',
                    'Brócoli',
                    'Coliflor',
                    'Repollo',
                    'Rábano',
                    'Rabanito',
                    'Pepino',
                    'Zapallito',
                    'Champiñón',
                    'Hongos',
                    'Acelga',
                    'Espinaca',
                    'Lechuga',
                    'Rúcula',
                    'Zanahoria',
                    'Remolacha',
                    'Papa',
                    'Batata',
                    'Zapallo',
                    'Calabaza',
                    'Berenjena',
                    'Tomate',
                    'Pimiento',
                    'Cebolla',
                    'Puerro',
                    'Cebollita de verdeo',
                    'Choclo',
                    'Arveja',
                    'Chaucha',
                    'Poroto',
                    'Alcaucil',
                ],
                'Especias' => [
                    'Perejil',
                    'Cilantro',
                    'Albahaca',
                    'Romero',
                    'Orégano',
                    'Tomillo',
                    'Salvia',
                    'Estragón',
                    'Eneldo',
                    'Laurel',
                    'Comino',
                    'Pimentón',
                    'Pimienta',
                    'Cúrcuma',
                    'Jengibre',
                    'Ajo',
                ],
                'Frutos Secos' => [
                    'Nuez',
                    'Almendra',
                    'Avellana',
                    'Maní',
                    'Pistacho',
                    'Castaña',
                    'Coco',
                    'Sésamo',
                    'Lino',
                    'Chía',
                    'Amaranto',
                    'Quinoa',
                    'Mijo',
                    'Avena',
                    'Arroz',
                    'Trigo',
                    'Centeno',
                    'Maíz',
                    'Cebada',
                    'Soja',
                    'Garbanzo',
                    'Lenteja',
                    'Poroto',
                    'Arveja',
                    'Alfalfa',
                    'Lupino',
                    'Guisante',
                    'Habas',
                    'Cacahuete',
                    'Castaña',
                    'Nuez',
                    'Avellana',
                    'Almendra',
                    'Pistacho',
                    'Anacardo',
                    'Piñón',
                    'Macadamia',
                    'Coco',
                    'Sésamo',
                    'Lino',
                    'Chía',
                    'Amaranto',
                    'Quinoa',
                    'Mijo',
                    'Avena',
                    'Arroz',
                    'Trigo',
                    'Centeno',
                    'Maíz',
                    'Cebada',
                    'Soja',
                    'Garbanzo',
                    'Lenteja',
                    'Poroto',
                    'Arveja',
                    'Alfalfa',
                    'Lupino',
                    'Guisante',
                    'Habas',
                    'Cacahuete',
                    'Castaña',
                    'Nuez',
                    'Avellana',
                    'Almendra',
                    'Pistacho',
                    'Anacardo',
                    'Piñón',
                    'Macadamia',
                    'Coco',
                    'Sésamo',
                    'Lino',
                    'Chía',
                    'Amaranto',
                    'Quinoa',
                    'Mijo',
                    'Avena',
                    'Arroz',
                    'Trigo',
                    'Centeno',
                    'Maíz',
                    'Cebada',
                    'Soja',
                    'Garbanzo',
                    'Lenteja',
                    'Poroto',
                    'Arveja',
                    'Alfalfa',
                ],
                'Carnes' => [
                    'Vaca',
                    'Cerdo',
                    'Pollo',
                    'Pavo',
                    'Cordero',

                ],
                'Embutidos' => [
                    'Salame',
                    'Jamón',
                    'Mortadela',
                    'Chorizo',
                    'Longaniza',
                    'Salchicha',
                    'Salchichón',
                    'Panceta',
                    'Bondiola',
                    'Lomo',
                    'Pechuga',
                    'Muslo',
                    'Ala',
                    'Pata',
                    'Cabeza',
                    'Riñón',
                    'Hígado',
                    'Corazón',
                    'Molleja',
                    'Chinchulín',
                    'Tripa',
                    'Morcilla',
                    'Chorizo',
                    'Salchicha',
                    'Salchichón',
                    'Panceta',
                    'Bondiola',
                    'Lomo',
                    'Pechuga',
                    'Muslo',
                    'Ala',
                    'Pata',
                    'Cabeza',
                    'Riñón',
                    'Hígado',
                    'Corazón',
                    'Molleja',
                    'Chinchulín',
                    'Tripa',
                    'Morcilla',
                    'Chorizo',
                    'Salchicha',
                    'Salchichón',
                    'Panceta',
                    'Bondiola',
                    'Lomo',
                    'Pechuga',
                    'Muslo',
                    'Ala',
                    'Pata',
                    'Cabeza',
                    'Riñón',
                    'Hígado',
                    'Corazón',
                    'Molleja',
                    'Chinchulín',
                    'Tripa',
                    'Morcilla',
                ],
                'Dulces y Mermeladas' => [
                    'Dulce de leche',
                    'Dulce de membrillo',
                    'Dulce de batata',
                    'Dulce de zapallo',
                    'Dulce de frutilla',
                    'Dulce de arándano',
                    'Dulce de cereza',
                    'Dulce de mora',
                    'Dulce de frambuesa',
                    'Dulce de mango',
                    'Dulce de papaya',
                    'Dulce de maracuyá',
                    'Dulce de naranja',
                    'Dulce de pomelo',
                    'Dulce de limón',
                    'Dulce de ananá',
                    'Dulce de banana',
                    'Dulce de manzana',
                    'Dulce de pera',
                    'Dulce de durazno',
                    'Dulce de ciruela',
                    'Dulce de uva',
                    'Dulce de sandía',
                    'Dulce de melón',
                    'Dulce de frutilla',
                    'Dulce de arándano',
                    'Dulce de cereza',
                    'Dulce de mora',
                    'Dulce de frambuesa',
                    'Dulce de mango',
                    'Dulce de papaya',
                    'Dulce de maracuyá',
                    'Dulce de naranja',
                    'Dulce de pomelo',
                    'Dulce de limón',
                    'Dulce de ananá',
                    'Dulce de banana',
                    'Dulce de manzana',
                    'Dulce de pera',
                    'Dulce de durazno',
                    'Dulce de ciruela',
                    'Dulce de uva',
                    'Dulce de sandía',
                    'Dulce de melón',
                ],
                'Panificacion' => [
                    'Pan',
                    'Pan de molde',
                    'Pan de salvado',
                    'Pan de centeno',
                    'Pan de semillas',
                    'Pan de campo',
                    'Pan de pita',
                    'Pan de hamburguesa',
                    'Pan de hot dog',
                    'Pan de viena',
                    'Pan de miga',
                    'Pan de leche',
                    'Pan de manteca',
                    'Pan de agua',
                    'Pan de masa madre',
                    'Pan de masa madre integral',
                ],
                'Snacks caseros' => [
                    'Galletitas',
                    'Galletitas de avena',
                    'Galletitas de arroz',
                    'Galletitas de maíz',
                    'Galletitas de centeno',
                    'Galletitas de salvado',
                    'Galletitas de semillas',
                    'Galletitas de chía',
                    'Galletitas de lino',
                    'Galletitas de sésamo',
                    'Galletitas de amaranto',
                    'Galletitas de quinoa',
                    'Galletitas de mijo',
                    'Galletitas de avena',
                    'Galletitas de arroz',
                    'Galletitas de maíz',
                    'Galletitas de centeno',
                    'Galletitas de salvado',
                    'Galletitas de semillas',
                    'Galletitas de chía',
                    'Galletitas de lino',
                    'Galletitas de sésamo',
                    'Galletitas de amaranto',
                    'Galletitas de quinoa',
                    'Galletitas de mijo',
                    'Alfajores de maizena',
                    'Alfajores de chocolate',
                    'Alfajores de dulce de leche',
                ],
                'Leche y huevos' => [
                    'Leche',
                    'Crema de leche',
                    'Queso cremoso',
                    'Queso en barra',
                    'Ricota',
                    'Huevos blancos',
                    'Huevos de campo',
                    'Huevos de codorniz',
                ],
                'Jugos naturales' => [
                    'Jugo de naranja',
                    'Jugo de pomelo',
                    'Jugo de limón',
                    'Jugo de ananá',
                    'Jugo de banana',
                    'Jugo de manzana',
                    'Jugo de pera',
                    'Jugo de durazno',
                    'Jugo de ciruela',
                    'Jugo de uva',
                    'Jugo de sandía',
                    'Jugo de melón',
                    'Jugo de frutilla',
                    'Jugo de arándano',
                    'Jugo de cereza',
                    'Jugo de mora',
                    'Jugo de frambuesa',
                    'Jugo de mango',
                    'Jugo de papaya',
                    'Jugo de maracuyá',
                ],
            ],
            'Artesanias' => [
                'Cerámica' => [
                    'Platos',
                    'Tazas',
                    'Teteras',
                    'Jarras',
                    'Bandejas',
                    'Bols',
                    'Macetas',
                    'Floreros',
                    'Ceniceros',
                    'Candelabros',
                    'Jaboneras',
                ],
                'Cuero' => [
                    'Billeteras',
                    'Carteras',
                    'Cinturones',
                    'Bolsos',
                    'Mochilas',
                    'Bolsas',
                    'Monederos',
                    'Porta cosméticos',
                    'Porta documentos',
                    'Porta tarjetas',
                    'Porta celular',
                    'Porta notebook',
                    'Porta tablet',
                    'Porta vinos',
                    'Porta botellas',
                    'Porta termos',
                    'Porta mates',
                    'Porta vasos',
                    'Porta cubiertos',
                    'Porta llaves',
                    'Porta paraguas',
                ],
                'Madera' => [
                    'Bandejas',
                    'Bols',
                    'Macetas',
                    'Floreros',
                    'Ceniceros',
                    'Candelabros',
                    'Jaboneras',
                    'Platos',
                    'Tazas',
                    'Teteras',
                    'Jarras',
                    'Bandejas',
                    'Bols',
                    'Macetas',
                    'Floreros',
                    'Ceniceros',
                    'Candelabros',
                    'Jaboneras',
                ],
            ],
            'Plantas' => [
                'Del Interior' => [
                    'Suculentas',
                    'Bonsai',
                    'Orquídeas',
                    'Bambú',
                    'Begonias',
                ],
                'Del Exterior' => [
                    'Cactus',
                    'Bonsai',
                    'Bambú',
                    'Orquídeas',
                    'Begonias',
                ],
            ],
        ];

        foreach ($families as $family => $categoies) {
            $familyNew = Family::create([
                'name' => $family,
            ]);

            foreach ($categoies as $category => $subcategories) {
                $categoryNew = Category::create([
                    'name' => $category,
                    'family_id' => $familyNew->id,
                ]);

                foreach ($subcategories as $subcategory) {
                    Subcategory::create([
                        'name' => $subcategory,
                        'category_id' => $categoryNew->id,
                    ]);
                }
            }

        }
    }
}
